# Generated by Django 5.2.5 on 2025-08-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_options_remove_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nick_in_game',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ник в игре'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='platform',
            field=models.CharField(blank=True, choices=[('playstation', 'PlayStation'), ('xbox', 'Xbox'), ('nintendo', 'Nintendo'), ('apple', 'Apple'), ('windows', 'Windows'), ('android', 'Android')], max_length=20, verbose_name='Платформа'),
        ),
    ]
