# Generated by Django 5.2.5 on 2025-08-13 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название скина')),
                ('image', models.ImageField(upload_to='skins/', verbose_name='Фото скина')),
                ('drop_chance', models.DecimalField(decimal_places=4, help_text='Шанс в диапазоне от 0.0001 до 1.0000', max_digits=5, verbose_name='Шанс выпадения')),
                ('rarity', models.CharField(choices=[('common', 'Обычный'), ('uncommon', 'Необычный'), ('rare', 'Редкий'), ('epic', 'Эпический'), ('legendary', 'Легендарный')], default='common', max_length=50, verbose_name='Редкость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skins', to='cases.case', verbose_name='Кейс')),
            ],
            options={
                'verbose_name': 'Скин',
                'verbose_name_plural': 'Скины',
                'ordering': ['case', '-drop_chance'],
            },
        ),
    ]
