# Generated by Django 5.2.5 on 2025-08-14 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('skins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('won_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выигрыша')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('delivered', 'Доставлено')], default='pending', max_length=20, verbose_name='Статус')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_wins', to='cases.case', verbose_name='Кейс')),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_wins', to='skins.skin', verbose_name='Скин')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_skins', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Скин пользователя',
                'verbose_name_plural': 'Скины пользователя',
                'ordering': ['-won_at'],
            },
        ),
    ]
