# Generated by Django 5.2.5 on 2025-08-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_loginpage_accountpage_intro_answerspage_intro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountpage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='answerspage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='depositpage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='historypage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='featured_cases_title',
        ),
        migrations.RemoveField(
            model_name='indexpage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='opencasepage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='requestspage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='scrollcasepage',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='statictemplatepage',
            name='content',
        ),
        migrations.DeleteModel(
            name='LoginPage',
        ),
    ]
